package GUI;


import Agent.TravelAgent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import message.msgFlightAvailability_Result_List;
import message.msgReqFlightAvailability;
import org.jdesktop.application.Action;
import sun.security.x509.AttributeNameEnumeration;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TravelAgentGUI.java
 *
 * Created on Oct 23, 2011, 4:12:19 PM
 */
/**
 *
 * @author henry
 */
public class TravelAgentGUI extends javax.swing.JFrame {
    
    private msgReqFlightAvailability msgReqFlightAva;
    private TravelAgent travelA;
    
    /** Creates new form TravelAgentGUI */
    public TravelAgentGUI(TravelAgent a) {
        super(a.getLocalName());
        travelA = a;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtOrigin_City = new javax.swing.JTextField();
        txtOrigin_Country = new javax.swing.JTextField();
        txtDestination_City = new javax.swing.JTextField();
        txtDestination_Country = new javax.swing.JTextField();
        txtOnWard_Date = new javax.swing.JTextField();
        txtReturn_Date = new javax.swing.JTextField();
        txtNo_Of_Passengers = new javax.swing.JTextField();
        txtBudget = new javax.swing.JTextField();
        btnReqFlightDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvaFlights = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jade_project.Jade_ProjectApp.class).getContext().getResourceMap(TravelAgentGUI.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        txtOrigin_City.setText(resourceMap.getString("txtOrigin_City.text")); // NOI18N
        txtOrigin_City.setName("txtOrigin_City"); // NOI18N

        txtOrigin_Country.setName("txtOrigin_Country"); // NOI18N

        txtDestination_City.setName("txtDestination_City"); // NOI18N

        txtDestination_Country.setName("txtDestination_Country"); // NOI18N

        txtOnWard_Date.setName("txtOnWard_Date"); // NOI18N

        txtReturn_Date.setName("txtReturn_Date"); // NOI18N

        txtNo_Of_Passengers.setName("txtNo_Of_Passengers"); // NOI18N

        txtBudget.setName("txtBudget"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(jade_project.Jade_ProjectApp.class).getContext().getActionMap(TravelAgentGUI.class, this);
        btnReqFlightDetails.setAction(actionMap.get("reqFlightDetails")); // NOI18N
        btnReqFlightDetails.setText(resourceMap.getString("btnReqFlightDetails.text")); // NOI18N
        btnReqFlightDetails.setName("btnReqFlightDetails"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblAvaFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "FlightNo", "Departure City", "Departure Time", "Arrival City", "Arrival Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAvaFlights.setName("tblAvaFlights"); // NOI18N
        jScrollPane1.setViewportView(tblAvaFlights);
        tblAvaFlights.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title0")); // NOI18N
        tblAvaFlights.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title1")); // NOI18N
        tblAvaFlights.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title2")); // NOI18N
        tblAvaFlights.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title3")); // NOI18N
        tblAvaFlights.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title4")); // NOI18N
        tblAvaFlights.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tblAvaFlights.columnModel.title5")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOnWard_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNo_Of_Passengers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtReturn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReqFlightDetails, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(txtOrigin_City, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrigin_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination_City, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtOrigin_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtOrigin_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDestination_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDestination_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtOnWard_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtReturn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNo_Of_Passengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReqFlightDetails)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showGUI(){
        pack();
        super.setVisible(true);
    }

    @Action
    public void reqFlightDetails() {
        //11-June-2011
        //for Jade
        //set up the message first
        msgReqFlightAvailability reqFlightAva = new msgReqFlightAvailability();
        reqFlightAva.setOrigin_City(txtOrigin_City.getText());
        reqFlightAva.setOrigin_Country(txtOrigin_Country.getText());
        reqFlightAva.setDestination_City(txtDestination_City.getText());
        reqFlightAva.setDestination_Country(txtDestination_Country.getText());
        reqFlightAva.setOnWard_Date(convertStringToDate(txtOnWard_Date.getText()));
        reqFlightAva.setReturn_Date(convertStringToDate(txtReturn_Date.getText()));
        reqFlightAva.setNo_Of_Traveller(Integer.valueOf(txtNo_Of_Passengers.getText()));
        reqFlightAva.setBudget(Integer.valueOf(txtBudget.getText()));
        
        travelA.getFlightDetails(reqFlightAva);
        
        //currently for events, 1 = getFlightAvailability
        //GuiEvent geGetFlightAvailability = new GuiEvent(this, 1); 
    
    
    }
    
    //utility function for conversion from string to Date
    public Date convertStringToDate(String sValue){
        //"11-June-07"
        DateFormat formatter ; 
        Date date = new Date(); 
        
        try{
            formatter = new SimpleDateFormat("dd-MMM-yy");
            date = (Date)formatter.parse(sValue);
        }
        catch(Exception ex){
            
        }
        
        return date;
    }
    
    public void notifyUser(String message) {
        JOptionPane.showMessageDialog (null, message);
    }
    
    public void displayAvaFlights(msgFlightAvailability_Result_List input){
        String[] header = { "Airline", "FlightNo", "Departure City", "Departure Date", "Arrival City", "Arrival Time"};
        
        Vector vheader = new Vector();
        vheader.add(header);
        Vector vcolList = new Vector();

        for(int i = 0; i < input.getSize(); i++){
            Vector col = new Vector();
            col.add(input.getByIndex(i).getAirliner());
            col.add(input.getByIndex(i).getFlightID());
            col.add(input.getByIndex(i).getDeparture_City());
            col.add(input.getByIndex(i).getDepartureDate().toString());
            col.add(input.getByIndex(i).getDestination_City());
            col.add(input.getByIndex(i).getArrivalDate().toString());
            vcolList.add(col);
        }
        
        tblAvaFlights = new JTable(vcolList, vheader);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReqFlightDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAvaFlights;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDestination_City;
    private javax.swing.JTextField txtDestination_Country;
    private javax.swing.JTextField txtNo_Of_Passengers;
    private javax.swing.JTextField txtOnWard_Date;
    private javax.swing.JTextField txtOrigin_City;
    private javax.swing.JTextField txtOrigin_Country;
    private javax.swing.JTextField txtReturn_Date;
    // End of variables declaration//GEN-END:variables
}
